//! AAF (Advanced Authoring Format) export — audio-post interchange for
//! Pro Tools / Avid.
//!
//! AAF is a binary Microsoft Compound-File (CFB) container wrapping the AAF
//! object model (Mobs, MobSlots, Sequences, SourceClips, EssenceDescriptors)
//! encoded via AAF "structured storage" persistence. Every conformant AAF file
//! must embed the full AAF **MetaDictionary** (hundreds of class/type/property
//! definitions) — and readers (pyaaf2, the Avid AAF SDK) require it on load.
//!
//! Rather than reimplement that fixed metadictionary, we embed a known-good
//! skeleton ([`TEMPLATE_AAF`]) generated by pyaaf2 — header + complete
//! metadictionary + an empty `ContentStorage.Mobs` set — and **append** our
//! dynamic objects (the CompositionMob, SourceMobs, Slots, Sequences,
//! SourceClips, descriptors, locators) into it with the `cfb` crate. The
//! object byte-structures we emit are replicated from a real pyaaf2 reference
//! file (see `tools/validate_aaf.py`).
//!
//! Module layout:
//! - [`ids`]    — AAF constant tables (class/property/type AUIDs, PIDs,
//!   stored-form codes), ported from pyaaf2 (MIT).
//! - [`encode`] — low-level CFB + structured-storage persistence (properties
//!   streams, value encoders, strong/weak reference + index streams).
//! - [`writer`] — walks the UltimateSlice [`crate::model::project::Project`]
//!   and builds the AAF object graph.

pub mod encode;
pub mod ids;
pub mod writer;

/// pyaaf2-generated skeleton: AAF header + full MetaDictionary + empty
/// `ContentStorage.Mobs`. The dynamic export appends Mobs into this container.
pub const TEMPLATE_AAF: &[u8] = include_bytes!("template.aaf");

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Cursor;

    /// Gate: the Rust `cfb` crate must be able to open pyaaf2's container and
    /// see the expected AAF top-level storages. If this fails the whole
    /// template-append strategy is invalid.
    #[test]
    fn cfb_opens_pyaaf2_template() {
        let comp = cfb::CompoundFile::open(Cursor::new(TEMPLATE_AAF.to_vec()))
            .expect("cfb should open the pyaaf2 AAF template");
        let roots: Vec<String> = comp
            .read_storage("/")
            .expect("read root storage")
            .map(|e| e.name().to_string())
            .collect();
        // pyaaf2 writes a MetaDictionary storage and a Header storage at root.
        assert!(
            roots.iter().any(|n| n.starts_with("MetaDictionary")),
            "root entries missing MetaDictionary: {roots:?}"
        );
        assert!(
            roots.iter().any(|n| n.starts_with("Header")),
            "root entries missing Header: {roots:?}"
        );
    }

    /// Gate: cfb must round-trip the container — add a storage + stream, save to
    /// a new buffer, reopen, and see the addition. This is what the writer does.
    #[test]
    fn cfb_round_trips_template_with_added_storage() {
        let mut comp = cfb::CompoundFile::open(Cursor::new(TEMPLATE_AAF.to_vec()))
            .expect("open template");
        comp.create_storage("/UsAafSmokeTest").expect("create storage");
        {
            use std::io::Write;
            let mut s = comp
                .create_stream("/UsAafSmokeTest/blob")
                .expect("create stream");
            s.write_all(b"ultimateslice").expect("write stream");
        }
        // Recover the backing buffer (into_inner flushes pending writes).
        let bytes = comp.into_inner().into_inner();
        let reopened =
            cfb::CompoundFile::open(Cursor::new(bytes)).expect("reopen modified container");
        assert!(reopened.exists("/UsAafSmokeTest/blob"));
    }
}
